# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Safe Network Explained
description: > # this means to ignore newlines until "baseurl:"
  The safe network can be difficult to understand. These explanations
  make it easy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://safe-network-explained.github.io" # the base hostname & protocol for your site
github_username:  safe-network-explained
permalink: :title

# Build settings
markdown: kramdown
